### ISSUE TITLE
Decidable but not Divisible?

### ISSUE THREAD

**Issue by tomjaguarpaw** [ekmett/contravariant#16]
Is it really the case that there are no interesting `Decidable`s that are not `Divisible`?  Is there a proof of that?

**Comment by ekmett** [comment]
No more than there are no `Alternative`s that aren't `Applicative`. You can have them. But yet, we still make the class `Alternative` with an `Applicative` superclass nonetheless.

Yes, such a class could exist. Just like we could have a `FunctorPlus` or `Plus`.

In a world where Haskell was good at deep accurate class hierarchies, we might even put it in as a superclass, but we're not in that world.

**Comment by ekmett** [comment]
Closing this as: "By design" for now.
