### ISSUE TITLE
Deriving Contravariant instances with Template Haskell?

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/contravariant#17]
Since `Functor` instances can be derived straightforwardly with `DeriveFunctor`, it stands to reason that the same could be done for `Contravariant` instances. I propose this algorithm, which is adapted from [the `DeriveFunctor` algorithm](http://git.haskell.org/ghc.git/blob/9f968e97a0de9c2509da00f6337b612dd72a0389:/compiler/typecheck/TcGenDeriv.hs#l1523) with one small twist:

```haskell
  $(fmap 'a 'b)          =  \x -> x     -- when b does not contain a
  $(fmap 'a 'a)          =  error "type variable in covariant position"
  $(fmap 'a '(b1,b2))    =  \x -> case x of (x1,x2) -> ($(fmap 'a 'b1) x1, $(fmap 'a 'b2) x2)
  $(fmap 'a '(T b1 b2))  =  fmap $(fmap 'a 'b2)   -- when a only occurs in the last parameter, b2
  $(fmap 'a '(b -> c))   =  \x b -> $(fmap 'a' 'c) (x ($(cofmap 'a 'b) b))

  $(cofmap 'a 'b)          =  \x -> x     -- when b does not contain a
  $(cofmap 'a 'a)          =  f
  $(cofmap 'a '(b1,b2))    =  \x -> case x of (x1,x2) -> ($(cofmap 'a 'b1) x1, $(cofmap 'a 'b2) x2)
  $(cofmap 'a '[b])        =  map $(cofmap 'a 'b)
  $(cofmap 'a '(T b1 b2))  =  fmap $(cofmap 'a 'b2)   -- when a only occurs in the last parameter, b2
  $(cofmap 'a '(b -> c))   =  \x b -> $(cofmap 'a' 'c) (x ($(fmap 'a 'c) b))
```

The only difference is that the generated code `error`s upon seeing a plain type variable in a covariant position.

Unfortunately, `Contravariant` is a bit funny in that sometimes there isn't a "canonical" `Contravariant` instance for a given data type. The typical example is `newtype Compose f g a = Compose (f (g a))`, which can have two different, legal `Contravariant` instances:

```haskell
instance (Functor f, Contravariant g) => Contravariant (Compose f g) where ...
instance (Contravariant f, Functor g) => Contravariant (Compose f g) where ...
```

And for something like `newtype Tripe f g h a = Triple (f (g (h a)))`, there are even more options:

```haskell
instance (Functor f,       Functor g,       Contravariant h) => Contravariant (Triple f g h) where ...
instance (Functor f,       Contravariant g, Functor h)       => Contravariant (Triple f g h) where ...
instance (Contravariant f, Functor g,       Functor h)       => Contravariant (Triple f g h) where ...
instance (Contravariant f, Contravariant g, Contravariant h) => Contravariant (Triple f g h) where ...
```

What strategy should a `Contravariant` deriver take when given nested type parameters? I doubt it could be smart enough to alternate between `Functor` and `Contravariant` constraints, so it seems like the only options would be to make them all `Functor`-constrained or all `Contravariant`-constrained.

I would argue that having them all be `Functor`-constrained might be preferable:
* With all `Contravariant` constraints, you'd hit an error every time a type parameter has its variance flipped an even number of times. If there was a data type like

 ```haskell
 newtype Flip f g h a = Flip (f (g (h a)) -> Int)
 ```

 then in order to mentally verify that `Flip` could not have a derived `Contravariant` instance, a programmer would have to count each type parameter of kind `* -> *`, as well as the arrow.

 `Functor`, on the other hand, doesn't switch the variance, so the only thing a programmer would have to count are the arrows.
* I'm not sure how many `Contravariant` instances there are in the wild that have `Contravariant` constraints. Doing a `grep` of [`hackage-packages-master`](https://github.com/bitemyapp/hackage-packages/), I could find such instances in the `contravariant` package itself, in [`comonad`](https://github.com/ekmett/comonad/blob/b6d182b4d4c24d7e2ee12226a49157906da26fdb/src/Data/Functor/Coproduct.hs#L61-64), in `lens`, and in `tagged-transformer`. I [have](https://github.com/andrewthad/yesod-table/blob/dd155d9d82e329cdc24d995d372c87fe988bd0a6/src/Yesod/Table.hs#L69-70) seen [many](http://hackage.haskell.org/package/for-free-0.1/docs/src/Control-ForFree.html#line-105) instances of [`Contravariant`](http://hackage.haskell.org/package/DysFRP-0.1/docs/src/Control-DysFRP-Internal.html#Handler) instance [which](http://hackage.haskell.org/package/discrimination-0.1/docs/src/Data-Discrimination-Sorting.html#Sort) rely on `Functor` constraints too. At best, this is anecdotal evidence.
* This pattern seems to be used by other generic programming algorithms. For example, `Generic1` relies on the derived type being a `Functor` instance when dealing with multiply nested data types with a type parameter at the end.

What do you think? Does this sound worth pursuing? Is the algorithm too _ad hoc_?

**Comment by RyanGlScott** [comment]
After thinking about this some more, I think that having `Contravariant` constraints is actually the more logical choice. It didn't occur to me earlier that you could also define `Functor` instances with `Contravariant` constraints:

```haskell
newtype ContraCompose f g a = ContraCompose { runContraCompose :: f (g a) }

instance (Contravariant f, Contravariant g) => Functor (ContraCompose f g) where
    fmap f = ContraCompose . contramap (contramap f) . runContraCompose
```

So imposing `Functor` constraints for `Functor` instances is arguably just as `ad hoc` of a choice. In fact, you still have to count the number of times the variance is flipped (due to the presence of `(->)`), so the variance point is moot.

With this in mind, using `Contravariant` constraints seems alright. There will be certain datatypes which won't be able to have derived `Contravariant` instances, but this applies equally to `DeriveFunctor` as well.

**Comment by ekmett** [comment]
Ultimately it is this polarity issue that makes any deriving system for contravariant functors rather messy.

When it was just functor, you could lie to yourself and pretend contravariant functors don't exist, but contravariant functors 'switch polarity' when they compose, so the story is a lot less compositional.

**Comment by ekmett** [comment]
If you really wanted to you could go the extra mile and check for the instance being present when using it for a particular concrete data type. that would capture co/contra variance properly for things like Maybe and [], Predicate, where only one of the two is possible then it is only things that are actual type parameters, where you can't do anything 'right' for there is a true ambiguity, so any choice is arbitrary.

In general I'm far more content to just not supply a generator than supply one that makes 'bad' decisions constantly. If we confine ourselves to saying things that are 'true' then we don't have to worry about folks calling us out on the infelicities.

**Comment by RyanGlScott** [comment]
> When it was just functor, you could lie to yourself and pretend contravariant functors don't exist, but contravariant functors 'switch polarity' when they compose, so the story is a lot less compositional.

That does seem to be the problem—deriving `Contravariant` is just fundamentally trickier than `Functor`. I think I'll take up your advice and just not supply a generator. :)
