### ISSUE TITLE
Broken links in Hackage documentation

### ISSUE THREAD

**Issue by bwignall** [ekmett/contravariant#24]
In https://hackage.haskell.org/package/contravariant-1.4/docs/Data-Functor-Contravariant.html , I see 74 instances of "file:///usr/local/Cellar" (e.g., "...even though the dual of a <code><a href="file:///usr/local/Cellar/ghc/7.10.2/share/doc/ghc/html/libraries/base-4.8.1.0/Data-Functor.html#t:Functor">Functor</a></code> is just a...").

As nothing looks unusual in https://github.com/ekmett/contravariant/blob/master/src/Data/Functor/Contravariant.hs , I suppose this is a problem on the Hackage side, so perhaps this is more an FYI than an Issue.

**Comment by glguy** [comment]
It looks like someone manually uploaded some incorrectly generated documentation. I've uploaded fixed documentation.

If you're seeing old documentation still it is due to the CDN caching. This can be avoided by adding a query string to the URL.
