### ISSUE TITLE
Add 'Invariant' functor

### ISSUE THREAD

**Issue by ChShersh** [ekmett/contravariant#29]
It may be useful to have this type class that corresponds to _invariant functors_:

```haskell
class Invariant f where
    invmap :: (b -> a) -> (a -> b) -> f a -> f b
```

Obviously most useful instance would be for `Endo a`. Because `Endo a` can't be neither `Functor` nor `Contravariant` and even not `Profunctor`. But sometimes it is desirable to have some sort of mapping on `Endo`. But of course I expect other applications of `Invariant`. Probably it is a good idea to create separate `invariant` package for this purpose. And at current moment I don't expect it to be more than 20 lines or something like that.

Careful reader may notice that `invmap` type is very similar to `Iso` from [lens](https://github.com/ekmett/lens) but lifted to some `*functor`. And even some laws are true for `Invariant`:

```
invmap id id = id
invmap f g . invmap g f = id
```

Maybe this fact can be used somehow or there already exist similar abstraction. But I'm not aware of it.

**Comment by RyanGlScott** [comment]
There's already the [`invariant`](http://hackage.haskell.org/package/invariant) package for this.

**Comment by ChShersh** [comment]
@RyanGlScott Oops, didn't find it. This is the fastest issue in my life :D
Okay, I guess it can be closed. Sorry for distracting.
Thus it was expected. Some math concepts are more likely already written in Haskell than some enterprise package. So you can expect this kind of stuff to be implemented by someone.
