### ISSUE TITLE
Day could be a comonad

### ISSUE THREAD

**Issue by safareli** [ekmett/contravariant#37]
Not sure how useful it could be, but I think Day f g is a Comonad given f and g are Comonads.

``` hs
extract :: (Comonad f, Comonad g) => Day f g a -> a
extract (Day fx gy xya) = xya (extract fx) (extract gy)

duplicate :: (Comonad f, Comonad g) => Day f g a -> Day f g (Day f g a)
duplicate (Day fx gy xya) = (Day fx gy \_ _ -> (Day fx gy xya))
 ```

This seems to be lawful.

**Comment by safareli** [comment]
http://blog.functorial.com/posts/2016-08-08-Comonad-And-Day-Convolution.html

**Comment by paf31** [comment]
I think you want _co_variant `Day`.

**Comment by ekmett** [comment]
`Day fx gy \_ _ -> (Day fx gy xya)`  <- the _'s there make me look askance at this definition.

You need to duplicate f and g separately, then you can fix this definition though, at least, as Phil notes, for covariant Day convolution.

**Comment by sjoerdvisscher** [comment]
There is a comonad instance already: https://hackage.haskell.org/package/kan-extensions-5.2/docs/src/Data.Functor.Day.html#line-103
