### ISSUE TITLE
Is this law incorrect?

### ISSUE THREAD

**Issue by barrucadu** [ekmett/contravariant#47]
https://github.com/ekmett/contravariant/blob/3e605d46ed342cac4428ce80c07255ee4a0ed7b9/src/Data/Functor/Contravariant/Divisible.hs#L584-L592

The comment says that we need to reassociate, but the `f'` in the third law there doesn't appear to be reassociating at all, as it's throwing away the `d` component.

Should it be `f' a = let (bc, d) = f a; (b, c) = g bc in (b, (c, d))`?

**Comment by ekmett** [comment]
Yes.

**Comment by barrucadu** [comment]
Cool, I'll submit a PR.
