### ISSUE TITLE
suggest a name for an invariant parent of Alt and Decidable

### ISSUE THREAD

**Issue by fommil** [ekmett/contravariant#55]
In scalaz I introduced an invariant parent of Alt and Decidable. I'm calling it `Derives`, but I don't like the name (it has a name collision with a more important thing called `Deriving`).

If you've ever seen UK tv, the potential name `AltAndDec` will bring [horrific images](https://en.wikipedia.org/wiki/Ant_%26_Dec) to mind :smile: ... do you have any suggestions?

**Comment by ekmett** [comment]
Have you named all 7+ flavors of invariant yet? ;)

I'd probably just say something self-descriptive like `InvariantApplicative` and `InvariantAlternative`, but I have little interest in packaging them myself.

**Comment by fommil** [comment]
Lol, I did start that way then threw them out and now left with only this one, which is the most practical. InvariantAlt is one I did consider... there is precedent since InvariantFunctor exists, even though the logic is a bit warped here since CovariantAlt isn't a thing.

InvariantAlt it is!

Certainly better than AltRight.
