### ISSUE TITLE
Build with GHC 7.0.x

### ISSUE THREAD

**Issue by mightybyte** [ekmett/contravariant#8]
Any chance we can get this package modified to build with 7.0.x?  Travis is giving me this build failure:

https://travis-ci.org/mightybyte/snaplet-postgresql-simple/jobs/35057195#L309

(contravariant is on line 309)

**Comment by glguy** [comment]
Contravariant 1.2.0.1 builds on 7.0.4. Please reopen this issue if you're still having issues.
